services:
  - type: web
    name: ytshortdown-scraper
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SCRAPER_API_KEY
        sync: false
      - key: PYTHONUNBUFFERED
        value: "1"